name: Close Issues Based on Labels

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue as not planned if labeled with '❌ 拒绝'
        if: github.event.label.name == '❌ 拒绝'
        uses: peter-evans/close-issue@v3
        with:
          state: closed
          reason: 'not_planned'
        env:
          GITHUB_TOKEN: ${{ secrets.SHEEP }}

      - name: Close issue as completed if labeled with '👌 完成'
        if: github.event.label.name == '👌 完成'
        uses: peter-evans/close-issue@v3
        with:
          state: closed
          reason: 'completed'
        env:
          GITHUB_TOKEN: ${{ secrets.SHEEP }}
